routes.py
from flask import render_template, redirect, url_for, Blueprint, request
from flask_login import current_user, login_user, logout_user, login_required
from models import User, Text, Activity
from forms import LoginForm, RegistrationForm, SpellCheckForm, HistoryForm, LogsForm
from database import db
import subprocess
import os
import re
from datetime import datetime

blue = Blueprint('blue', __name__)


@blue.route('/')
@blue.route('/index')
@login_required
def index():
    return render_template('index.html', title='AppSec - Assignments 2 and 3')


@blue.route('/login', methods=['GET', 'POST'])
def login():
    # if current_user.is_authenticated:
    #    return redirect(url_for('blue.spell_check'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data, form.phone.data):
            return render_template('login.html', title='Log In', form=form, connection_status='Incorrect')
        login_user(user, remember=form.remember_me.data)
        activity = Activity(user_id=user.id)
        db.session.add(activity)
        db.session.commit()
        return render_template('login.html', title='Log In', form=form, connection_status='Success')
    return render_template('login.html', title='Log In', form=form)


@blue.route('/logout')
def logout():
    user = User.query.filter_by(username=current_user.username).first()
    activity = Activity.query.filter_by(user_id=user.id).order_by(Activity.id.desc()).first()
    activity.log_out = datetime.utcnow()
    db.session.commit()
    logout_user()
    return redirect(url_for('blue.login'))


@blue.route('/register', methods=['GET', 'POST'])
def register():
    # if current_user.is_authenticated:
    #    return redirect(url_for('blue.spell_check'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, phone=form.phone.data)
        if User.query.filter_by(username=form.username.data).first() is not None:
            return render_template('register.html', title='Register', form=form, registration_status='Failure')
        user.set_password(form.password.data, form.phone.data)
        db.session.add(user)
        db.session.commit()
        return render_template('register.html', title='Register', form=form, registration_status='Success')
    return render_template('register.html', title='Register', form=form)


@blue.route('/spell_check', methods=['GET', 'POST'])
@login_required
def spell_check():
    form = SpellCheckForm()
    if form.validate_on_submit() and request.method == 'POST':
        file = open("input.txt", "w")
        file.write(form.text_to_check.data)
        file.close()
        command = ["./spell_check", "input.txt", "wordlist.txt"]
        sub = subprocess.Popen(command, stdout=subprocess.PIPE)
        misspelled = sub.communicate()[0].decode("utf-8").replace("\n", ", ")[:-2]
        os.remove("input.txt")
        supplied_text = form.text_to_check.data
        form.text_to_check.data = ""

        # Requirements for assignment 3
        # Adding submitted text to database
        user = User.query.filter_by(username=current_user.username).first()
        text = Text(before_spellcheck=supplied_text, after_spellcheck=misspelled, user_id=user.id)
        db.session.add(text)
        db.session.commit()
        return render_template('spell_check.html', title='Spell Check', form=form, input=supplied_text, output=misspelled)
    else:
        return render_template('spell_check.html', title='Spell Check', form=form)


@blue.route('/history', methods=['GET', 'POST'])
@login_required
def history():
    user = User.query.filter_by(username=current_user.username).first()
    form = HistoryForm()
    if user.username == 'admin':
        if form.validate_on_submit() and request.method == 'POST':
            requested_user = User.query.filter_by(username=form.username.data).first()
            text_history = requested_user.texts.all()
            return render_template('history.html', title='History', form=form, total_queries=len(text_history), user=requested_user, texts=text_history)
        else:
            return render_template('history.html', title='History', form=form)
    else:
        text_history = user.texts.all()
        return render_template('history.html', title='History', form=form, total_queries=len(text_history), user=user, texts=text_history)


@blue.route('/history/<query_id>', methods=['GET'])
@login_required
def history_query(query_id):
    user = User.query.filter_by(username=current_user.username).first()
    current_text_id = re.findall('\d+', query_id)
    if user.username == 'admin':
        current_text = Text.query.filter_by(id=current_text_id[0]).first()
    else:
        current_text = Text.query.filter_by(id=current_text_id[0], user_id=user.id).first()

    if current_text is None:
        return redirect(url_for('blue.history'))
    else:
        return render_template('query.html', title='Query', user=user, text=current_text)


@blue.route('/login_history', methods=['GET', 'POST'])
@login_required
def login_history():
    if current_user.username == 'admin':
        form = LogsForm()
        if form.validate_on_submit() and request.method == 'POST':
            requested_user = User.query.filter_by(username=form.username.data).first()
            logs_history = requested_user.activities.all()
            return render_template('login_history.html', title='Login History', form=form, user=requested_user, activities=logs_history)
        else:
            return render_template('login_history.html', title='Login History', form=form)
    else:
        return render_template('index.html', title='AppSec - Assignments 2 and 3')

templates/base.html
<html>
    <head>
      {% if title %}
      <title>{{ title }} - Application Security</title>
      {% else %}
      <title>Welcome to Assignment 2 and 3</title>
      {% endif %}
    </head>
    <body>
        <div>Spell Check: <a href="/index">Home</a> <a href="/login">Log In</a> <a href="/register">Register</a> <a href="/spell_check">Spell Checker</a> <a href="/history">History</a> <a href="/login_history">Logs History</a> <a href="/logout">Log Out</a></div>
        <hr>
        {% block content %}{% endblock %}
    </body>
</html>

templates/csrf_vuln.html
<html>
<head>
    <title>CSRF Vulnerability Attempt</title>
</head>
<body>
    <form action="http://127.0.0.1:5000/login" method="POST">
        <input type="hidden" id="uname" name="username" value="csrf"/>
        <input type="hidden" id="pword" name="password" value="csrf"/>
        <input type="hidden" id="2fa" name="phone" value="1234567890"/>
    </form>
    <script>
        document.forms[0].submit();
    </script>
</body>
</html>

templates/history.html
{% extends "base.html" %}

{% block content %}
    {% if user is defined %}
    <h1>User: {{ user.username }}</h1>
    <hr>
    <p id="numqueries"> Total number of queries: {{ total_queries }}</p>
    {% for text in texts %}
    <p>
        <a id="query{{ text.id }}" href="/history/query{{ text.id }}">Query {{ text.id }}</a>
    </p>
    {% endfor %}
    {% endif %}
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

templates/index.html
<html>
<body>
    <h1>Application Security</h1>
    <h2>Assignments 2 and 3</h2>
    <p>Already a user? <a href="{{ url_for('blue.login') }}">Login</a></p>
    <p>New user? <a href="{{ url_for('blue.register') }}">Click to Register!</a></p>
</body>
</html>

templates/login.html
{% extends "base.html" %}

{% block content %}
    <h1>Log In</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <p id="result">{{ connection_status }}</p>
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.phone.label }}<br>
            {{ form.phone(size=32) }}<br>
            {% for error in form.phone.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
        <p>{{ form.submit() }}</p>
    </form>
    <p>New user? <a href="{{ url_for('blue.register') }}">Click to Register!</a></p>
{% endblock %}

templates/login_history.html
{% extends "base.html" %}

{% block content %}
<form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
    {% if user is defined %}
    <h1>User: {{ user.username }}</h1>
    <hr>
    {% for activity in activities %}
        <p id="login{{ activity.id }}_time">Login: {{ activity.log_in }}</p>
        {% if activity.log_out == None %}
            <p id="logout{{ activity.id }}_time">Logout: N/A</p>
        {% else %}
            <p id="logout{{ activity.id }}_time">Logout: {{ activity.log_out }}</p>
        {% endif %}
    {% endfor %}
    {% endif %}
{% endblock %}

templates/query.html
{% extends "base.html" %}

{% block content %}
    <p id="queryid"><b>Query Number:</b> {{ text.id }}</p>
    <p id="username"><b>Username:</b> {{ text.author.username }}</p>
    <p id="querytext"><b>Submitted text:</b> {{ text.before_spellcheck }}</p>
    <p id="queryresults"><b>Results:</b> {{ text.after_spellcheck }}</p>
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block content %}
    <h1>Register</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p id="success">{{ registration_status }}</p>
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.phone.label }}<br>
            {{ form.phone(size=32) }}<br>
            {% for error in form.phone.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

templates/spell_check.html
{% extends "base.html" %}
{% block content %}
    <h1>Spell Check</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.text_to_check.label }}<br>
            {{ form.text_to_check(size=64) }}<br>
            {% for error in form.text_to_check.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p id="inputtext"> {{ input }} </p>
        <p id="outputtext"> {{ output }} </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}